/* StudentKart — My Reports */
(function(){
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const meta={pending:["Pending","fa-clock","warning"],reviewed:["Reviewed","fa-eye","info"],resolved:["Resolved","fa-circle-check","success"],dismissed:["Dismissed","fa-circle-xmark","muted"]};
function styles(){if(document.getElementById("studentkartMyReportsStyles"))return;const s=document.createElement("style");s.id="studentkartMyReportsStyles";s.textContent=".sk-my-reports-card{border:1px solid #dce7ed!important;background:#fbfdfc!important}.sk-my-reports-card b{color:#102a43}.sk-report-status{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:800}.sk-report-status.warning{background:#fff4df;color:#a86300}.sk-report-status.info{background:#eaf4ff;color:#2169a8}.sk-report-status.success{background:#e7f7ef;color:#187548}.sk-report-status.muted{background:#eef1f3;color:#65727a}.sk-my-report-item{border:1px solid #dce7ed;border-radius:16px;padding:14px;background:#fff;margin-bottom:10px}.sk-my-report-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.sk-my-report-title{font-weight:800;color:#102a43;font-size:14px}.sk-my-report-meta{margin-top:5px;color:#718083;font-size:11px;line-height:1.6}.sk-my-report-details{margin-top:9px;padding:10px;border-radius:10px;background:#f8fbff;color:#52636b;font-size:11px;line-height:1.5}.sk-my-report-actions{margin-top:11px;display:flex;gap:8px;flex-wrap:wrap}";document.head.appendChild(s)}
async function open(){
const user=window.currentUser||(typeof currentUser!=="undefined"?currentUser:null);if(!user){window.showToast?.("Please login to view your reports","warning");return}styles();
let modal=document.getElementById("myReportsModal");
if(!modal){modal=document.createElement("div");modal.id="myReportsModal";modal.className="modal hidden";modal.innerHTML='<div class="modal-overlay" data-close-my-reports></div><div class="modal-content" style="max-width:680px"><div class="settings-page-header"><div class="settings-title-wrap"><div class="settings-icon"><i class="fas fa-flag"></i></div><div><span class="section-label">ACCOUNT</span><h2>My Reports</h2><p>Track the reports you have submitted.</p></div></div><button type="button" class="modal-close" data-close-my-reports>&times;</button></div><div id="myReportsList"><div class="sk-admin-empty">Loading...</div></div></div>';document.body.appendChild(modal);modal.querySelectorAll("[data-close-my-reports]").forEach(x=>x.addEventListener("click",()=>modal.classList.add("hidden")))}
modal.classList.remove("hidden");const list=modal.querySelector("#myReportsList");list.innerHTML='<div class="sk-admin-empty"><i class="fas fa-spinner fa-spin"></i> Loading your reports...</div>';
const {data,error}=await supabaseClient.from("reports").select("id,product_id,reason,details,status,created_at,reviewed_at").eq("reporter_id",user.id).order("created_at",{ascending:false}).limit(50);
if(error){list.innerHTML='<div class="sk-admin-empty">Could not load your reports.<br><small>'+esc(error.message)+'</small></div>';return}
const rows=data||[],products={};const ids=[...new Set(rows.map(r=>r.product_id).filter(Boolean))];
if(ids.length){const pr=await supabaseClient.from("products").select("id,name,price,location,seller,moderation_status").in("id",ids);if(!pr.error)(pr.data||[]).forEach(p=>products[p.id]=p)}
if(!rows.length){list.innerHTML='<div class="sk-admin-empty"><i class="fas fa-flag"></i><br><strong>No reports yet</strong><br><small>Reports you submit will appear here.</small></div>';return}
list.innerHTML=rows.map(r=>{const p=products[r.product_id],m=meta[r.status]||meta.pending;return '<article class="sk-my-report-item"><div class="sk-my-report-head"><div><div class="sk-my-report-title">'+esc(p?.name||"Listing unavailable")+'</div><div class="sk-my-report-meta">Reason: '+esc(r.reason)+'<br>Submitted: '+esc(new Date(r.created_at).toLocaleString("en-IN"))+(r.reviewed_at?'<br>Updated: '+esc(new Date(r.reviewed_at).toLocaleString("en-IN")):"")+'</div></div><span class="sk-report-status '+m[2]+'"><i class="fas '+m[1]+'"></i> '+m[0]+'</span></div>'+(r.details?'<div class="sk-my-report-details">'+esc(r.details)+'</div>':"")+(p?'<div class="sk-my-report-meta">Listing status: <strong>'+esc(p.moderation_status||"active")+'</strong>'+(p.price!=null?' · ₹'+esc(Number(p.price).toLocaleString("en-IN")):"")+'</div>':"")+(p?'<div class="sk-my-report-actions"><button type="button" class="btn btn-outline" data-view-my-report="'+esc(p.id)+'"><i class="fas fa-eye"></i> View Listing</button></div>':"")+'</article>'}).join("");
list.querySelectorAll("[data-view-my-report]").forEach(btn=>btn.addEventListener("click",async()=>{if(typeof window.StudentKartOpenProductDetails!=="function"){window.showToast?.("Listing details are unavailable","error");return}modal.classList.add("hidden");await window.StudentKartOpenProductDetails(btn.dataset.viewMyReport)}))
}
function bind(){styles();const grid=document.querySelector("#settingsModal .settings-grid");if(!grid||document.getElementById("settingsMyReportsButton"))return;const section=document.createElement("section");section.className="settings-group sk-my-reports-card";section.innerHTML='<button class="settings-section-button" type="button" id="settingsMyReportsButton"><span><i class="fas fa-flag"></i><b>My Reports</b><small>Track the reports you submitted on listings</small></span><i class="fas fa-chevron-right"></i></button>';grid.appendChild(section);section.querySelector("#settingsMyReportsButton").addEventListener("click",open)}
window.StudentKartMyReports={open};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();setInterval(bind,1500);
})();